"""fleet and providers (Phase 9): the fleet's view of the workers it provisions (pool, variant,
provision and registration times, the enrollment token a provisioned worker registers with), budget holds on queued GPU tasks, and `fleet_costs` — the
append-only platform record of each stopped worker's provisioned, busy and idle time (§25).

Revision ID: 0002
Revises: 0001
Create Date: 2026-10-04 22:58:25.369699
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0002"
down_revision: str | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "fleet_costs",
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("worker_id", sa.Uuid(), nullable=False),
        sa.Column("provider_id", sa.Uuid(), nullable=True),
        sa.Column("provider_kind", sa.String(), nullable=True),
        sa.Column("pool_id", sa.String(), nullable=True),
        sa.Column("gpu_type", sa.String(), nullable=False),
        sa.Column("period_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("period_end", sa.DateTime(timezone=True), nullable=False),
        sa.Column("provisioned_seconds", sa.Double(), nullable=False),
        sa.Column("busy_seconds", sa.Double(), nullable=False),
        sa.Column("idle_seconds", sa.Double(), nullable=False),
        sa.Column("price_per_hour_usd", sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column("provisioned_usd", sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column("idle_usd", sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["provider_id"], ["gpu_providers.id"], name=op.f("fk_fleet_costs_provider_id_gpu_providers")
        ),
        sa.ForeignKeyConstraint(["worker_id"], ["gpu_workers.id"], name=op.f("fk_fleet_costs_worker_id_gpu_workers")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_fleet_costs")),
    )
    op.create_index(op.f("ix_fleet_costs_period_end"), "fleet_costs", ["period_end"], unique=False)
    op.create_index(op.f("ix_fleet_costs_worker_id"), "fleet_costs", ["worker_id"], unique=False)
    op.add_column("gpu_tasks", sa.Column("held_reason", sa.String(), nullable=True))
    op.add_column(
        "gpu_providers",
        sa.Column(
            "config", postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False
        ),
    )
    op.add_column("gpu_workers", sa.Column("provider_kind", sa.String(), nullable=True))
    op.add_column("gpu_workers", sa.Column("pool_id", sa.String(), nullable=True))
    op.add_column("gpu_workers", sa.Column("variant", sa.String(), nullable=True))
    op.add_column("gpu_workers", sa.Column("provisioned_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("gpu_workers", sa.Column("registered_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("worker_enrollment_tokens", sa.Column("worker_id", sa.Uuid(), nullable=True))
    op.create_foreign_key(
        op.f("fk_worker_enrollment_tokens_worker_id_gpu_workers"),
        "worker_enrollment_tokens",
        "gpu_workers",
        ["worker_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###
    # fleet_costs is append-only like cost_ledger (ce_append_only from migration 0001's rules)
    op.execute(
        "CREATE TRIGGER ce_fleet_costs_append_only BEFORE UPDATE OR DELETE ON fleet_costs "
        "FOR EACH ROW EXECUTE FUNCTION ce_append_only()"
    )


def downgrade() -> None:
    op.execute("DROP TRIGGER IF EXISTS ce_fleet_costs_append_only ON fleet_costs")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_worker_enrollment_tokens_worker_id_gpu_workers"), "worker_enrollment_tokens", type_="foreignkey"
    )
    op.drop_column("worker_enrollment_tokens", "worker_id")
    op.drop_column("gpu_workers", "registered_at")
    op.drop_column("gpu_workers", "provisioned_at")
    op.drop_column("gpu_workers", "variant")
    op.drop_column("gpu_workers", "pool_id")
    op.drop_column("gpu_workers", "provider_kind")
    op.drop_column("gpu_tasks", "held_reason")
    op.drop_column("gpu_providers", "config")
    op.drop_index(op.f("ix_fleet_costs_worker_id"), table_name="fleet_costs")
    op.drop_index(op.f("ix_fleet_costs_period_end"), table_name="fleet_costs")
    op.drop_table("fleet_costs")
    # ### end Alembic commands ###
