"""Phase 12: memory loop, research, templates, brand, caption review, packaging and exports.

Additive columns only (no data rewrite): the embedding model beside every vector (embeddings of
different models are never compared), persistent research sources and facts (what was read and
why it failed), the claim ledger's latest check (evidence quotes, closed-book flags, overrides),
immutable versioned spec templates, packaging candidates/limits/generator, export metadata, and
the caption translation review (`rejected` joins the review states).

Revision ID: 0004
Revises: 0003
Create Date: 2026-10-05 21:02:01.667521
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0004"
down_revision: str | None = "0003"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("brand_kits", sa.Column("created_by", sa.Uuid(), nullable=True))
    op.add_column("brand_kits", sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(op.f("fk_brand_kits_created_by_users"), "brand_kits", "users", ["created_by"], ["id"])
    op.add_column(
        "captions",
        sa.Column(
            "route", postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False
        ),
    )
    op.add_column("captions", sa.Column("reviewed_by", sa.Uuid(), nullable=True))
    op.add_column("captions", sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("captions", sa.Column("review_note", sa.String(), nullable=True))
    op.create_foreign_key(op.f("fk_captions_reviewed_by_users"), "captions", "users", ["reviewed_by"], ["id"])
    op.add_column("claims", sa.Column("last_version_id", sa.Uuid(), nullable=True))
    op.add_column("claims", sa.Column("segment_key", sa.String(), nullable=True))
    op.add_column(
        "claims",
        sa.Column(
            "evidence", postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False
        ),
    )
    op.add_column(
        "claims",
        sa.Column(
            "reasons", postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False
        ),
    )
    op.add_column("claims", sa.Column("closed_book", sa.Boolean(), server_default=sa.text("false"), nullable=False))
    op.add_column("claims", sa.Column("blocking", sa.Boolean(), server_default=sa.text("false"), nullable=False))
    op.add_column("claims", sa.Column("overridable", sa.Boolean(), server_default=sa.text("true"), nullable=False))
    op.add_column("claims", sa.Column("detected", sa.Boolean(), server_default=sa.text("false"), nullable=False))
    op.add_column("claims", sa.Column("override_at", sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(
        op.f("fk_claims_org_id_last_version_id_video_versions"),
        "claims",
        "video_versions",
        ["org_id", "last_version_id"],
        ["org_id", "id"],
    )
    op.add_column("creator_memory_items", sa.Column("embedding_model", sa.String(), nullable=True))
    op.add_column("creator_usage_events", sa.Column("hook_embedding_model", sa.String(), nullable=True))
    op.create_index(
        "ix_creator_usage_events_hook_embedding_hnsw",
        "creator_usage_events",
        ["hook_embedding"],
        unique=False,
        postgresql_using="hnsw",
        postgresql_ops={"hook_embedding": "vector_cosine_ops"},
    )
    op.add_column("exports", sa.Column("version_id", sa.Uuid(), nullable=True))
    op.add_column("exports", sa.Column("preset_id", sa.String(), nullable=True))
    op.add_column(
        "exports", sa.Column("caption_ids", postgresql.ARRAY(sa.Uuid()), server_default=sa.text("'{}'"), nullable=False)
    )
    op.add_column(
        "exports",
        sa.Column(
            "metadata_doc",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
    )
    op.add_column("exports", sa.Column("metadata_artifact_id", sa.Uuid(), nullable=True))
    op.create_index(op.f("ix_exports_version_id"), "exports", ["version_id"], unique=False)
    op.create_foreign_key(
        op.f("fk_exports_org_id_version_id_video_versions"),
        "exports",
        "video_versions",
        ["org_id", "version_id"],
        ["org_id", "id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("fk_exports_org_id_metadata_artifact_id_artifacts"),
        "exports",
        "artifacts",
        ["org_id", "metadata_artifact_id"],
        ["org_id", "id"],
    )
    op.add_column("packaging", sa.Column("job_id", sa.Uuid(), nullable=True))
    op.add_column(
        "packaging",
        sa.Column(
            "thumbnail_candidates",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
    )
    op.add_column(
        "packaging",
        sa.Column(
            "limits", postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False
        ),
    )
    op.add_column(
        "packaging",
        sa.Column(
            "issues", postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False
        ),
    )
    op.add_column(
        "packaging",
        sa.Column(
            "generator", postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False
        ),
    )
    op.add_column("packaging", sa.Column("approved_by", sa.Uuid(), nullable=True))
    op.add_column("packaging", sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(op.f("fk_packaging_approved_by_users"), "packaging", "users", ["approved_by"], ["id"])
    op.create_foreign_key(
        op.f("fk_packaging_org_id_job_id_generation_jobs"),
        "packaging",
        "generation_jobs",
        ["org_id", "job_id"],
        ["org_id", "id"],
    )
    op.add_column("research_facts", sa.Column("chunk_index", sa.Integer(), server_default="0", nullable=False))
    op.add_column("research_facts", sa.Column("embedding_model", sa.String(), nullable=True))
    op.add_column("research_sources", sa.Column("mime", sa.String(), nullable=True))
    op.add_column("research_sources", sa.Column("bytes", sa.BigInteger(), nullable=True))
    op.add_column("research_sources", sa.Column("language", sa.String(), nullable=True))
    op.add_column("research_sources", sa.Column("note_text", sa.String(), nullable=True))
    op.add_column(
        "research_sources",
        sa.Column(
            "extract", postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False
        ),
    )
    op.add_column("research_sources", sa.Column("error", postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column("research_sources", sa.Column("fact_count", sa.Integer(), server_default="0", nullable=False))
    op.add_column("research_sources", sa.Column("embedding_model", sa.String(), nullable=True))
    op.add_column("research_sources", sa.Column("job_id", sa.Uuid(), nullable=True))
    op.add_column("research_sources", sa.Column("created_by", sa.Uuid(), nullable=True))
    op.create_foreign_key(
        op.f("fk_research_sources_created_by_users"), "research_sources", "users", ["created_by"], ["id"]
    )
    op.create_foreign_key(
        op.f("fk_research_sources_org_id_job_id_generation_jobs"),
        "research_sources",
        "generation_jobs",
        ["org_id", "job_id"],
        ["org_id", "id"],
    )
    op.add_column("spec_templates", sa.Column("description", sa.String(), server_default="", nullable=False))
    op.add_column("spec_templates", sa.Column("version", sa.Integer(), server_default="1", nullable=False))
    op.add_column("spec_templates", sa.Column("parent_template_id", sa.Uuid(), nullable=True))
    op.add_column("spec_templates", sa.Column("source_version_id", sa.Uuid(), nullable=True))
    op.add_column(
        "spec_templates",
        sa.Column("paths", postgresql.ARRAY(sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    )
    op.add_column("spec_templates", sa.Column("body_digest", sa.String(), server_default="", nullable=False))
    op.add_column("spec_templates", sa.Column("created_by", sa.Uuid(), nullable=True))
    op.add_column("spec_templates", sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(
        op.f("fk_spec_templates_org_id_parent_template_id_spec_templates"),
        "spec_templates",
        "spec_templates",
        ["org_id", "parent_template_id"],
        ["org_id", "id"],
    )
    op.create_foreign_key(op.f("fk_spec_templates_created_by_users"), "spec_templates", "users", ["created_by"], ["id"])
    op.create_foreign_key(
        op.f("fk_spec_templates_org_id_source_version_id_video_versions"),
        "spec_templates",
        "video_versions",
        ["org_id", "source_version_id"],
        ["org_id", "id"],
        ondelete="SET NULL",
    )
    op.drop_constraint(op.f("ck_captions_review_state"), "captions", type_="check")
    op.create_check_constraint(
        op.f("ck_captions_review_state"), "captions", "review_state IN ('n/a', 'pending', 'approved', 'rejected')"
    )
    op.add_column("generation_jobs", sa.Column("output", postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # thumbnails and export files are kept alive by their packaging and exports (retention, §12.10)
    op.drop_constraint(op.f("ck_artifact_refs_ref_type"), "artifact_refs", type_="check")
    op.create_check_constraint(
        op.f("ck_artifact_refs_ref_type"),
        "artifact_refs",
        "ref_type IN ('build_manifest', 'take', 'render', 'identity_pack', 'world_plate', 'voice_conditioning', 'creator_test', 'memory_snapshot', 'plan_report', 'asset', 'packaging', 'export')",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    op.execute("DELETE FROM artifact_refs WHERE ref_type IN ('packaging', 'export')")
    op.drop_constraint(op.f("ck_artifact_refs_ref_type"), "artifact_refs", type_="check")
    op.create_check_constraint(
        op.f("ck_artifact_refs_ref_type"),
        "artifact_refs",
        "ref_type IN ('build_manifest', 'take', 'render', 'identity_pack', 'world_plate', 'voice_conditioning', 'creator_test', 'memory_snapshot', 'plan_report', 'asset')",
    )
    op.drop_column("generation_jobs", "output")
    op.execute("UPDATE captions SET review_state = 'pending' WHERE review_state = 'rejected'")
    op.drop_constraint(op.f("ck_captions_review_state"), "captions", type_="check")
    op.create_check_constraint(
        op.f("ck_captions_review_state"), "captions", "review_state IN ('n/a', 'pending', 'approved')"
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_spec_templates_org_id_source_version_id_video_versions"), "spec_templates", type_="foreignkey"
    )
    op.drop_constraint(op.f("fk_spec_templates_created_by_users"), "spec_templates", type_="foreignkey")
    op.drop_constraint(
        op.f("fk_spec_templates_org_id_parent_template_id_spec_templates"), "spec_templates", type_="foreignkey"
    )
    op.drop_column("spec_templates", "archived_at")
    op.drop_column("spec_templates", "created_by")
    op.drop_column("spec_templates", "body_digest")
    op.drop_column("spec_templates", "paths")
    op.drop_column("spec_templates", "source_version_id")
    op.drop_column("spec_templates", "parent_template_id")
    op.drop_column("spec_templates", "version")
    op.drop_column("spec_templates", "description")
    op.drop_constraint(
        op.f("fk_research_sources_org_id_job_id_generation_jobs"), "research_sources", type_="foreignkey"
    )
    op.drop_constraint(op.f("fk_research_sources_created_by_users"), "research_sources", type_="foreignkey")
    op.drop_column("research_sources", "created_by")
    op.drop_column("research_sources", "job_id")
    op.drop_column("research_sources", "embedding_model")
    op.drop_column("research_sources", "fact_count")
    op.drop_column("research_sources", "error")
    op.drop_column("research_sources", "extract")
    op.drop_column("research_sources", "note_text")
    op.drop_column("research_sources", "language")
    op.drop_column("research_sources", "bytes")
    op.drop_column("research_sources", "mime")
    op.drop_column("research_facts", "embedding_model")
    op.drop_column("research_facts", "chunk_index")
    op.drop_constraint(op.f("fk_packaging_org_id_job_id_generation_jobs"), "packaging", type_="foreignkey")
    op.drop_constraint(op.f("fk_packaging_approved_by_users"), "packaging", type_="foreignkey")
    op.drop_column("packaging", "approved_at")
    op.drop_column("packaging", "approved_by")
    op.drop_column("packaging", "generator")
    op.drop_column("packaging", "issues")
    op.drop_column("packaging", "limits")
    op.drop_column("packaging", "thumbnail_candidates")
    op.drop_column("packaging", "job_id")
    op.drop_constraint(op.f("fk_exports_org_id_metadata_artifact_id_artifacts"), "exports", type_="foreignkey")
    op.drop_constraint(op.f("fk_exports_org_id_version_id_video_versions"), "exports", type_="foreignkey")
    op.drop_index(op.f("ix_exports_version_id"), table_name="exports")
    op.drop_column("exports", "metadata_artifact_id")
    op.drop_column("exports", "metadata_doc")
    op.drop_column("exports", "caption_ids")
    op.drop_column("exports", "preset_id")
    op.drop_column("exports", "version_id")
    op.drop_index(
        "ix_creator_usage_events_hook_embedding_hnsw",
        table_name="creator_usage_events",
        postgresql_using="hnsw",
        postgresql_ops={"hook_embedding": "vector_cosine_ops"},
    )
    op.drop_column("creator_usage_events", "hook_embedding_model")
    op.drop_column("creator_memory_items", "embedding_model")
    op.drop_constraint(op.f("fk_claims_org_id_last_version_id_video_versions"), "claims", type_="foreignkey")
    op.drop_column("claims", "override_at")
    op.drop_column("claims", "detected")
    op.drop_column("claims", "overridable")
    op.drop_column("claims", "blocking")
    op.drop_column("claims", "closed_book")
    op.drop_column("claims", "reasons")
    op.drop_column("claims", "evidence")
    op.drop_column("claims", "segment_key")
    op.drop_column("claims", "last_version_id")
    op.drop_constraint(op.f("fk_captions_reviewed_by_users"), "captions", type_="foreignkey")
    op.drop_column("captions", "review_note")
    op.drop_column("captions", "reviewed_at")
    op.drop_column("captions", "reviewed_by")
    op.drop_column("captions", "route")
    op.drop_constraint(op.f("fk_brand_kits_created_by_users"), "brand_kits", type_="foreignkey")
    op.drop_column("brand_kits", "archived_at")
    op.drop_column("brand_kits", "created_by")
    # ### end Alembic commands ###
