# syntax=docker/dockerfile:1.7
# GENERATED by scripts/gen_worker_dockerfiles.py from infra/docker/families.yaml and the plugin manifests —
# do not edit by hand. The `image` GPU runtime family (§36, ADR 0052): one build target per variant.
#   docker build -f infra/docker/worker-image.Dockerfile --target <variant> -t creator-engine/worker-image:<variant> .
# Variants: image_diffusers (z_image_turbo, qwen_image_edit).
# Status: lint-checked only; never built with its CUDA stack here (no GPU, rule 5). Weights come from the
# model cache at run time (MODEL_CACHE_DIR, a network volume or local disk), never from the image.

FROM ghcr.io/astral-sh/uv@sha256:df4cae8f3a96d175e2e5f992e597550000edbe78fdc2594d5cd8de1a217f504c AS uv

# ---------------------------------------------------------------- image_diffusers
FROM nvidia/cuda:12.8.1-cudnn-runtime-ubuntu24.04@sha256:ac55d124da4882b497f732d8dfd9a702d5447a5f29d08d56da6f64f0a1eb34bc AS image_diffusers
ENV DEBIAN_FRONTEND=noninteractive PYTHONUNBUFFERED=1 UV_COMPILE_BYTECODE=1 UV_LINK_MODE=copy \
    UV_PYTHON_INSTALL_DIR=/opt/python VIRTUAL_ENV=/app/.venv PATH=/app/.venv/bin:$PATH
RUN apt-get update && apt-get install -y --no-install-recommends ca-certificates ffmpeg git curl \
    && rm -rf /var/lib/apt/lists/* && useradd --create-home --uid 10001 ce && mkdir -p /models /app \
    && chown ce:ce /models
COPY --from=uv /uv /usr/local/bin/uv
RUN --mount=type=secret,id=extra_ca,required=false \
    if [ -s /run/secrets/extra_ca ]; then export SSL_CERT_FILE=/run/secrets/extra_ca; fi; \
    uv python install 3.10 && uv venv /app/.venv --python 3.10
RUN --mount=type=cache,target=/root/.cache/uv --mount=type=secret,id=extra_ca,required=false \
    if [ -s /run/secrets/extra_ca ]; then export SSL_CERT_FILE=/run/secrets/extra_ca; fi; \
    uv pip install --index-url https://download.pytorch.org/whl/cu128 torch==2.8.0 torchvision==0.23.0 torchaudio==2.8.0
# https://github.com/QwenLM/Qwen-Image@6b5e1f5cec987d404be5ac6657db3b9aacb56a89: license reference only (not installed)
# https://github.com/Tongyi-MAI/Z-Image@26f23eda626ffadda020b04ff79488e1d72004cd: license reference only (not installed)
RUN --mount=type=cache,target=/root/.cache/uv --mount=type=secret,id=extra_ca,required=false \
    if [ -s /run/secrets/extra_ca ]; then export SSL_CERT_FILE=/run/secrets/extra_ca; fi; \
    uv pip install --extra-index-url https://download.pytorch.org/whl/cu128 diffusers==0.40.0 transformers accelerate sentencepiece
COPY packages/py/ce_contracts /src/packages/py/ce_contracts
COPY packages/py/ce_plugin_kit /src/packages/py/ce_plugin_kit
COPY packages/py/ce_worker /src/packages/py/ce_worker
COPY plugins/image/qwen_image_edit /src/plugins/image/qwen_image_edit
COPY plugins/image/z_image /src/plugins/image/z_image
RUN --mount=type=cache,target=/root/.cache/uv --mount=type=secret,id=extra_ca,required=false \
    if [ -s /run/secrets/extra_ca ]; then export SSL_CERT_FILE=/run/secrets/extra_ca; fi; \
    uv pip install /src/packages/py/ce_contracts /src/packages/py/ce_plugin_kit /src/packages/py/ce_worker /src/plugins/image/qwen_image_edit /src/plugins/image/z_image
ENV WORKER_RUNTIME_FAMILY=image WORKER_ADAPTERS=z_image_turbo,qwen_image_edit APP_ENV=prod MODEL_CACHE_DIR=/models
WORKDIR /app
USER ce
CMD ["python", "-m", "ce_worker"]
