# syntax=docker/dockerfile:1.7
# GENERATED by scripts/gen_worker_dockerfiles.py from infra/docker/families.yaml and the plugin manifests —
# do not edit by hand. The `talking_head` worker profile (cutover §14): one GPU instance, one worker per family.
#   docker build -f infra/docker/worker-profile-talking_head.Dockerfile -t creator-engine/worker-profile:talking_head .
# Components: infinitetalk (wan: infinitetalk), chatterbox (tts: chatterbox, chatterbox_turbo, chatterbox_multilingual).
# Each keeps its own environment (they pin different torch stacks); `python -m ce_worker.multi` starts one
# `ce_worker` per family with that family's WORKER_TOKEN_<FAMILY> and exits when one of them stops.
# Status: lint-checked only; never built with its CUDA stack here (no GPU, rule 5). Weights come from the
# model cache at run time (MODEL_CACHE_DIR), never from the image.

FROM ghcr.io/astral-sh/uv@sha256:df4cae8f3a96d175e2e5f992e597550000edbe78fdc2594d5cd8de1a217f504c AS uv

# ---------------------------------------------------------------- infinitetalk_env
FROM nvidia/cuda:12.8.1-cudnn-devel-ubuntu24.04@sha256:24c8e3581ea6330038b0d374920721983312627f8adbfcf390bdb4b399d280ed AS infinitetalk_env
ENV DEBIAN_FRONTEND=noninteractive PYTHONUNBUFFERED=1 UV_COMPILE_BYTECODE=1 UV_LINK_MODE=copy \
    UV_PYTHON_INSTALL_DIR=/opt/python VIRTUAL_ENV=/opt/env/infinitetalk PATH=/opt/env/infinitetalk/bin:$PATH
RUN apt-get update && apt-get install -y --no-install-recommends ca-certificates ffmpeg git curl \
    && rm -rf /var/lib/apt/lists/* && useradd --create-home --uid 10001 ce && mkdir -p /models /app \
    && chown ce:ce /models
COPY --from=uv /uv /usr/local/bin/uv
RUN --mount=type=secret,id=extra_ca,required=false \
    if [ -s /run/secrets/extra_ca ]; then export SSL_CERT_FILE=/run/secrets/extra_ca; fi; \
    uv python install 3.10 && uv venv /opt/env/infinitetalk --python 3.10
RUN --mount=type=cache,target=/root/.cache/uv --mount=type=secret,id=extra_ca,required=false \
    if [ -s /run/secrets/extra_ca ]; then export SSL_CERT_FILE=/run/secrets/extra_ca; fi; \
    uv pip install --index-url https://download.pytorch.org/whl/cu121 torch==2.4.1 torchvision==0.19.1 torchaudio==2.4.1
RUN git init -q /opt/upstream/InfiniteTalk && git -C /opt/upstream/InfiniteTalk remote add origin https://github.com/MeiGen-AI/InfiniteTalk \
    && git -C /opt/upstream/InfiniteTalk fetch -q --depth 1 origin 50aa0a94184315407a991ae804d9b58d6d311ba8 \
    && git -C /opt/upstream/InfiniteTalk checkout -q FETCH_HEAD
RUN --mount=type=cache,target=/root/.cache/uv --mount=type=secret,id=extra_ca,required=false \
    if [ -s /run/secrets/extra_ca ]; then export SSL_CERT_FILE=/run/secrets/extra_ca; fi; \
    uv pip install --extra-index-url https://download.pytorch.org/whl/cu121 -r /opt/upstream/InfiniteTalk/requirements.txt
RUN --mount=type=cache,target=/root/.cache/uv --mount=type=secret,id=extra_ca,required=false \
    if [ -s /run/secrets/extra_ca ]; then export SSL_CERT_FILE=/run/secrets/extra_ca; fi; \
    uv pip install --extra-index-url https://download.pytorch.org/whl/cu121 --no-build-isolation-package flash_attn xformers==0.0.28 flash_attn==2.7.4.post1 "misaki[en]" librosa pyloudnorm
COPY packages/py/ce_contracts /src/packages/py/ce_contracts
COPY packages/py/ce_plugin_kit /src/packages/py/ce_plugin_kit
COPY packages/py/ce_worker /src/packages/py/ce_worker
COPY plugins/avatar/infinitetalk /src/plugins/avatar/infinitetalk
RUN --mount=type=cache,target=/root/.cache/uv --mount=type=secret,id=extra_ca,required=false \
    if [ -s /run/secrets/extra_ca ]; then export SSL_CERT_FILE=/run/secrets/extra_ca; fi; \
    uv pip install /src/packages/py/ce_contracts /src/packages/py/ce_plugin_kit /src/packages/py/ce_worker /src/plugins/avatar/infinitetalk

# ---------------------------------------------------------------- chatterbox_env
FROM nvidia/cuda:12.8.1-cudnn-runtime-ubuntu24.04@sha256:ac55d124da4882b497f732d8dfd9a702d5447a5f29d08d56da6f64f0a1eb34bc AS chatterbox_env
ENV DEBIAN_FRONTEND=noninteractive PYTHONUNBUFFERED=1 UV_COMPILE_BYTECODE=1 UV_LINK_MODE=copy \
    UV_PYTHON_INSTALL_DIR=/opt/python VIRTUAL_ENV=/opt/env/chatterbox PATH=/opt/env/chatterbox/bin:$PATH
RUN apt-get update && apt-get install -y --no-install-recommends ca-certificates ffmpeg git curl \
    && rm -rf /var/lib/apt/lists/* && useradd --create-home --uid 10001 ce && mkdir -p /models /app \
    && chown ce:ce /models
COPY --from=uv /uv /usr/local/bin/uv
RUN --mount=type=secret,id=extra_ca,required=false \
    if [ -s /run/secrets/extra_ca ]; then export SSL_CERT_FILE=/run/secrets/extra_ca; fi; \
    uv python install 3.10 && uv venv /opt/env/chatterbox --python 3.10
RUN --mount=type=cache,target=/root/.cache/uv --mount=type=secret,id=extra_ca,required=false \
    if [ -s /run/secrets/extra_ca ]; then export SSL_CERT_FILE=/run/secrets/extra_ca; fi; \
    uv pip install --index-url https://download.pytorch.org/whl/cu124 torch==2.6.0 torchaudio==2.6.0
RUN git init -q /opt/upstream/Perth && git -C /opt/upstream/Perth remote add origin https://github.com/resemble-ai/Perth \
    && git -C /opt/upstream/Perth fetch -q --depth 1 origin ff1c8ac55a976971245cdd53c18d6131ca00d993 \
    && git -C /opt/upstream/Perth checkout -q FETCH_HEAD
RUN --mount=type=cache,target=/root/.cache/uv --mount=type=secret,id=extra_ca,required=false \
    if [ -s /run/secrets/extra_ca ]; then export SSL_CERT_FILE=/run/secrets/extra_ca; fi; \
    uv pip install --extra-index-url https://download.pytorch.org/whl/cu124 /opt/upstream/Perth
RUN git init -q /opt/upstream/chatterbox && git -C /opt/upstream/chatterbox remote add origin https://github.com/resemble-ai/chatterbox \
    && git -C /opt/upstream/chatterbox fetch -q --depth 1 origin 5de7a54aa4e5e2baadb0182dde554908b48b85c2 \
    && git -C /opt/upstream/chatterbox checkout -q FETCH_HEAD
RUN --mount=type=cache,target=/root/.cache/uv --mount=type=secret,id=extra_ca,required=false \
    if [ -s /run/secrets/extra_ca ]; then export SSL_CERT_FILE=/run/secrets/extra_ca; fi; \
    uv pip install --extra-index-url https://download.pytorch.org/whl/cu124 /opt/upstream/chatterbox
COPY packages/py/ce_contracts /src/packages/py/ce_contracts
COPY packages/py/ce_plugin_kit /src/packages/py/ce_plugin_kit
COPY packages/py/ce_worker /src/packages/py/ce_worker
COPY plugins/voice/chatterbox /src/plugins/voice/chatterbox
RUN --mount=type=cache,target=/root/.cache/uv --mount=type=secret,id=extra_ca,required=false \
    if [ -s /run/secrets/extra_ca ]; then export SSL_CERT_FILE=/run/secrets/extra_ca; fi; \
    uv pip install /src/packages/py/ce_contracts /src/packages/py/ce_plugin_kit /src/packages/py/ce_worker /src/plugins/voice/chatterbox

# ---------------------------------------------------------------- talking_head
FROM nvidia/cuda:12.8.1-cudnn-devel-ubuntu24.04@sha256:24c8e3581ea6330038b0d374920721983312627f8adbfcf390bdb4b399d280ed AS talking_head
ENV DEBIAN_FRONTEND=noninteractive PYTHONUNBUFFERED=1
RUN apt-get update && apt-get install -y --no-install-recommends ca-certificates curl ffmpeg git \
    && rm -rf /var/lib/apt/lists/* && useradd --create-home --uid 10001 ce && mkdir -p /models /app \
    && chown ce:ce /models
COPY --from=infinitetalk_env /opt/python /opt/python
COPY --from=infinitetalk_env /opt/env/infinitetalk /opt/env/infinitetalk
COPY --from=infinitetalk_env /opt/upstream/InfiniteTalk /opt/upstream/InfiniteTalk
COPY --from=chatterbox_env /opt/python /opt/python
COPY --from=chatterbox_env /opt/env/chatterbox /opt/env/chatterbox
COPY --from=chatterbox_env /opt/upstream/Perth /opt/upstream/Perth
COPY --from=chatterbox_env /opt/upstream/chatterbox /opt/upstream/chatterbox
ENV WORKER_COMPONENTS=wan,tts \
    WORKER_PROFILE=talking_head \
    WORKER_PYTHON_WAN=/opt/env/infinitetalk/bin/python \
    WORKER_ADAPTERS_WAN=infinitetalk \
    WORKER_PYTHONPATH_WAN=/opt/upstream/InfiniteTalk \
    WORKER_PYTHON_TTS=/opt/env/chatterbox/bin/python \
    WORKER_ADAPTERS_TTS=chatterbox,chatterbox_turbo,chatterbox_multilingual \
    APP_ENV=prod \
    MODEL_CACHE_DIR=/models
WORKDIR /app
USER ce
CMD ["/opt/env/infinitetalk/bin/python", "-m", "ce_worker.multi"]
