# syntax=docker/dockerfile:1.7
# GENERATED by scripts/gen_worker_dockerfiles.py from infra/docker/families.yaml and the plugin manifests —
# do not edit by hand. The `tts` GPU runtime family (§36, ADR 0052): one build target per variant.
#   docker build -f infra/docker/worker-tts.Dockerfile --target <variant> -t creator-engine/worker-tts:<variant> .
# Variants: chatterbox (chatterbox, chatterbox_turbo, chatterbox_multilingual), qwen_tts (qwen3_tts), voxcpm (voxcpm2).
# Status: lint-checked only; never built with its CUDA stack here (no GPU, rule 5). Weights come from the
# model cache at run time (MODEL_CACHE_DIR, a network volume or local disk), never from the image.

FROM ghcr.io/astral-sh/uv@sha256:df4cae8f3a96d175e2e5f992e597550000edbe78fdc2594d5cd8de1a217f504c AS uv

# ---------------------------------------------------------------- chatterbox
FROM nvidia/cuda:12.8.1-cudnn-runtime-ubuntu24.04@sha256:ac55d124da4882b497f732d8dfd9a702d5447a5f29d08d56da6f64f0a1eb34bc AS chatterbox
ENV DEBIAN_FRONTEND=noninteractive PYTHONUNBUFFERED=1 UV_COMPILE_BYTECODE=1 UV_LINK_MODE=copy \
    UV_PYTHON_INSTALL_DIR=/opt/python VIRTUAL_ENV=/app/.venv PATH=/app/.venv/bin:$PATH
RUN apt-get update && apt-get install -y --no-install-recommends ca-certificates ffmpeg git curl \
    && rm -rf /var/lib/apt/lists/* && useradd --create-home --uid 10001 ce && mkdir -p /models /app \
    && chown ce:ce /models
COPY --from=uv /uv /usr/local/bin/uv
RUN --mount=type=secret,id=extra_ca,required=false \
    if [ -s /run/secrets/extra_ca ]; then export SSL_CERT_FILE=/run/secrets/extra_ca; fi; \
    uv python install 3.10 && uv venv /app/.venv --python 3.10
RUN --mount=type=cache,target=/root/.cache/uv --mount=type=secret,id=extra_ca,required=false \
    if [ -s /run/secrets/extra_ca ]; then export SSL_CERT_FILE=/run/secrets/extra_ca; fi; \
    uv pip install --index-url https://download.pytorch.org/whl/cu124 torch==2.6.0 torchaudio==2.6.0
RUN git init -q /opt/upstream/Perth && git -C /opt/upstream/Perth remote add origin https://github.com/resemble-ai/Perth \
    && git -C /opt/upstream/Perth fetch -q --depth 1 origin ff1c8ac55a976971245cdd53c18d6131ca00d993 \
    && git -C /opt/upstream/Perth checkout -q FETCH_HEAD
RUN --mount=type=cache,target=/root/.cache/uv --mount=type=secret,id=extra_ca,required=false \
    if [ -s /run/secrets/extra_ca ]; then export SSL_CERT_FILE=/run/secrets/extra_ca; fi; \
    uv pip install --extra-index-url https://download.pytorch.org/whl/cu124 /opt/upstream/Perth
RUN git init -q /opt/upstream/chatterbox && git -C /opt/upstream/chatterbox remote add origin https://github.com/resemble-ai/chatterbox \
    && git -C /opt/upstream/chatterbox fetch -q --depth 1 origin 5de7a54aa4e5e2baadb0182dde554908b48b85c2 \
    && git -C /opt/upstream/chatterbox checkout -q FETCH_HEAD
RUN --mount=type=cache,target=/root/.cache/uv --mount=type=secret,id=extra_ca,required=false \
    if [ -s /run/secrets/extra_ca ]; then export SSL_CERT_FILE=/run/secrets/extra_ca; fi; \
    uv pip install --extra-index-url https://download.pytorch.org/whl/cu124 /opt/upstream/chatterbox
COPY packages/py/ce_contracts /src/packages/py/ce_contracts
COPY packages/py/ce_plugin_kit /src/packages/py/ce_plugin_kit
COPY packages/py/ce_worker /src/packages/py/ce_worker
COPY plugins/voice/chatterbox /src/plugins/voice/chatterbox
RUN --mount=type=cache,target=/root/.cache/uv --mount=type=secret,id=extra_ca,required=false \
    if [ -s /run/secrets/extra_ca ]; then export SSL_CERT_FILE=/run/secrets/extra_ca; fi; \
    uv pip install /src/packages/py/ce_contracts /src/packages/py/ce_plugin_kit /src/packages/py/ce_worker /src/plugins/voice/chatterbox
ENV WORKER_RUNTIME_FAMILY=tts WORKER_ADAPTERS=chatterbox,chatterbox_turbo,chatterbox_multilingual APP_ENV=prod MODEL_CACHE_DIR=/models
WORKDIR /app
USER ce
CMD ["python", "-m", "ce_worker"]

# ---------------------------------------------------------------- qwen_tts
FROM nvidia/cuda:12.8.1-cudnn-runtime-ubuntu24.04@sha256:ac55d124da4882b497f732d8dfd9a702d5447a5f29d08d56da6f64f0a1eb34bc AS qwen_tts
ENV DEBIAN_FRONTEND=noninteractive PYTHONUNBUFFERED=1 UV_COMPILE_BYTECODE=1 UV_LINK_MODE=copy \
    UV_PYTHON_INSTALL_DIR=/opt/python VIRTUAL_ENV=/app/.venv PATH=/app/.venv/bin:$PATH
RUN apt-get update && apt-get install -y --no-install-recommends ca-certificates ffmpeg git curl \
    && rm -rf /var/lib/apt/lists/* && useradd --create-home --uid 10001 ce && mkdir -p /models /app \
    && chown ce:ce /models
COPY --from=uv /uv /usr/local/bin/uv
RUN --mount=type=secret,id=extra_ca,required=false \
    if [ -s /run/secrets/extra_ca ]; then export SSL_CERT_FILE=/run/secrets/extra_ca; fi; \
    uv python install 3.10 && uv venv /app/.venv --python 3.10
RUN --mount=type=cache,target=/root/.cache/uv --mount=type=secret,id=extra_ca,required=false \
    if [ -s /run/secrets/extra_ca ]; then export SSL_CERT_FILE=/run/secrets/extra_ca; fi; \
    uv pip install --index-url https://download.pytorch.org/whl/cu128 torch==2.8.0 torchvision==0.23.0 torchaudio==2.8.0
RUN --mount=type=cache,target=/root/.cache/uv --mount=type=secret,id=extra_ca,required=false \
    if [ -s /run/secrets/extra_ca ]; then export SSL_CERT_FILE=/run/secrets/extra_ca; fi; \
    uv pip install --extra-index-url https://download.pytorch.org/whl/cu128 qwen-tts==0.1.1
COPY packages/py/ce_contracts /src/packages/py/ce_contracts
COPY packages/py/ce_plugin_kit /src/packages/py/ce_plugin_kit
COPY packages/py/ce_worker /src/packages/py/ce_worker
COPY plugins/voice/qwen3_tts /src/plugins/voice/qwen3_tts
RUN --mount=type=cache,target=/root/.cache/uv --mount=type=secret,id=extra_ca,required=false \
    if [ -s /run/secrets/extra_ca ]; then export SSL_CERT_FILE=/run/secrets/extra_ca; fi; \
    uv pip install /src/packages/py/ce_contracts /src/packages/py/ce_plugin_kit /src/packages/py/ce_worker /src/plugins/voice/qwen3_tts
ENV WORKER_RUNTIME_FAMILY=tts WORKER_ADAPTERS=qwen3_tts APP_ENV=prod MODEL_CACHE_DIR=/models
WORKDIR /app
USER ce
CMD ["python", "-m", "ce_worker"]

# ---------------------------------------------------------------- voxcpm
FROM nvidia/cuda:12.8.1-cudnn-runtime-ubuntu24.04@sha256:ac55d124da4882b497f732d8dfd9a702d5447a5f29d08d56da6f64f0a1eb34bc AS voxcpm
ENV DEBIAN_FRONTEND=noninteractive PYTHONUNBUFFERED=1 UV_COMPILE_BYTECODE=1 UV_LINK_MODE=copy \
    UV_PYTHON_INSTALL_DIR=/opt/python VIRTUAL_ENV=/app/.venv PATH=/app/.venv/bin:$PATH
RUN apt-get update && apt-get install -y --no-install-recommends ca-certificates ffmpeg git curl \
    && rm -rf /var/lib/apt/lists/* && useradd --create-home --uid 10001 ce && mkdir -p /models /app \
    && chown ce:ce /models
COPY --from=uv /uv /usr/local/bin/uv
RUN --mount=type=secret,id=extra_ca,required=false \
    if [ -s /run/secrets/extra_ca ]; then export SSL_CERT_FILE=/run/secrets/extra_ca; fi; \
    uv python install 3.10 && uv venv /app/.venv --python 3.10
RUN --mount=type=cache,target=/root/.cache/uv --mount=type=secret,id=extra_ca,required=false \
    if [ -s /run/secrets/extra_ca ]; then export SSL_CERT_FILE=/run/secrets/extra_ca; fi; \
    uv pip install --index-url https://download.pytorch.org/whl/cu128 torch==2.8.0 torchvision==0.23.0 torchaudio==2.8.0
RUN --mount=type=cache,target=/root/.cache/uv --mount=type=secret,id=extra_ca,required=false \
    if [ -s /run/secrets/extra_ca ]; then export SSL_CERT_FILE=/run/secrets/extra_ca; fi; \
    uv pip install --extra-index-url https://download.pytorch.org/whl/cu128 voxcpm==2.0.3
COPY packages/py/ce_contracts /src/packages/py/ce_contracts
COPY packages/py/ce_plugin_kit /src/packages/py/ce_plugin_kit
COPY packages/py/ce_worker /src/packages/py/ce_worker
COPY plugins/voice/voxcpm2 /src/plugins/voice/voxcpm2
RUN --mount=type=cache,target=/root/.cache/uv --mount=type=secret,id=extra_ca,required=false \
    if [ -s /run/secrets/extra_ca ]; then export SSL_CERT_FILE=/run/secrets/extra_ca; fi; \
    uv pip install /src/packages/py/ce_contracts /src/packages/py/ce_plugin_kit /src/packages/py/ce_worker /src/plugins/voice/voxcpm2
ENV WORKER_RUNTIME_FAMILY=tts WORKER_ADAPTERS=voxcpm2 APP_ENV=prod MODEL_CACHE_DIR=/models
WORKDIR /app
USER ce
CMD ["python", "-m", "ce_worker"]
