# syntax=docker/dockerfile:1.7
# GENERATED by scripts/gen_worker_dockerfiles.py from infra/docker/families.yaml and the plugin manifests —
# do not edit by hand. The `post` GPU runtime family (§36, ADR 0052): one build target per variant.
#   docker build -f infra/docker/worker-post.Dockerfile --target <variant> -t creator-engine/worker-post:<variant> .
# Variants: watermarks (videoseal, audioseal), seedvr2 (seedvr2_3b), rife (rife_425).
# Status: lint-checked only; never built with its CUDA stack here (no GPU, rule 5). Weights come from the
# model cache at run time (MODEL_CACHE_DIR, a network volume or local disk), never from the image.

FROM ghcr.io/astral-sh/uv@sha256:df4cae8f3a96d175e2e5f992e597550000edbe78fdc2594d5cd8de1a217f504c AS uv

# ---------------------------------------------------------------- watermarks
FROM nvidia/cuda:12.8.1-cudnn-runtime-ubuntu24.04@sha256:ac55d124da4882b497f732d8dfd9a702d5447a5f29d08d56da6f64f0a1eb34bc AS watermarks
ENV DEBIAN_FRONTEND=noninteractive PYTHONUNBUFFERED=1 UV_COMPILE_BYTECODE=1 UV_LINK_MODE=copy \
    UV_PYTHON_INSTALL_DIR=/opt/python VIRTUAL_ENV=/app/.venv PATH=/app/.venv/bin:$PATH
RUN apt-get update && apt-get install -y --no-install-recommends ca-certificates ffmpeg git curl \
    && rm -rf /var/lib/apt/lists/* && useradd --create-home --uid 10001 ce && mkdir -p /models /app \
    && chown ce:ce /models
COPY --from=uv /uv /usr/local/bin/uv
RUN --mount=type=secret,id=extra_ca,required=false \
    if [ -s /run/secrets/extra_ca ]; then export SSL_CERT_FILE=/run/secrets/extra_ca; fi; \
    uv python install 3.10 && uv venv /app/.venv --python 3.10
RUN --mount=type=cache,target=/root/.cache/uv --mount=type=secret,id=extra_ca,required=false \
    if [ -s /run/secrets/extra_ca ]; then export SSL_CERT_FILE=/run/secrets/extra_ca; fi; \
    uv pip install --index-url https://download.pytorch.org/whl/cu128 torch==2.8.0 torchvision==0.23.0 torchaudio==2.8.0
RUN --mount=type=cache,target=/root/.cache/uv --mount=type=secret,id=extra_ca,required=false \
    if [ -s /run/secrets/extra_ca ]; then export SSL_CERT_FILE=/run/secrets/extra_ca; fi; \
    uv pip install --extra-index-url https://download.pytorch.org/whl/cu128 audioseal==0.2.0 videoseal==1.0.1
COPY packages/py/ce_contracts /src/packages/py/ce_contracts
COPY packages/py/ce_plugin_kit /src/packages/py/ce_plugin_kit
COPY packages/py/ce_worker /src/packages/py/ce_worker
COPY plugins/provenance/neural_watermarks /src/plugins/provenance/neural_watermarks
RUN --mount=type=cache,target=/root/.cache/uv --mount=type=secret,id=extra_ca,required=false \
    if [ -s /run/secrets/extra_ca ]; then export SSL_CERT_FILE=/run/secrets/extra_ca; fi; \
    uv pip install /src/packages/py/ce_contracts /src/packages/py/ce_plugin_kit /src/packages/py/ce_worker /src/plugins/provenance/neural_watermarks
ENV WORKER_RUNTIME_FAMILY=post WORKER_ADAPTERS=videoseal,audioseal APP_ENV=prod MODEL_CACHE_DIR=/models
WORKDIR /app
USER ce
CMD ["python", "-m", "ce_worker"]

# ---------------------------------------------------------------- seedvr2
FROM nvidia/cuda:12.8.1-cudnn-devel-ubuntu24.04@sha256:24c8e3581ea6330038b0d374920721983312627f8adbfcf390bdb4b399d280ed AS seedvr2
ENV DEBIAN_FRONTEND=noninteractive PYTHONUNBUFFERED=1 UV_COMPILE_BYTECODE=1 UV_LINK_MODE=copy \
    UV_PYTHON_INSTALL_DIR=/opt/python VIRTUAL_ENV=/app/.venv PATH=/app/.venv/bin:$PATH
RUN apt-get update && apt-get install -y --no-install-recommends ca-certificates ffmpeg git curl \
    && rm -rf /var/lib/apt/lists/* && useradd --create-home --uid 10001 ce && mkdir -p /models /app \
    && chown ce:ce /models
COPY --from=uv /uv /usr/local/bin/uv
RUN --mount=type=secret,id=extra_ca,required=false \
    if [ -s /run/secrets/extra_ca ]; then export SSL_CERT_FILE=/run/secrets/extra_ca; fi; \
    uv python install 3.10 && uv venv /app/.venv --python 3.10
RUN --mount=type=cache,target=/root/.cache/uv --mount=type=secret,id=extra_ca,required=false \
    if [ -s /run/secrets/extra_ca ]; then export SSL_CERT_FILE=/run/secrets/extra_ca; fi; \
    uv pip install --index-url https://download.pytorch.org/whl/cu121 torch==2.3.0 torchvision==0.18.0
RUN git init -q /opt/upstream/SeedVR && git -C /opt/upstream/SeedVR remote add origin https://github.com/ByteDance-Seed/SeedVR \
    && git -C /opt/upstream/SeedVR fetch -q --depth 1 origin e4de8c24441a67e1b7df56abea10645059bb1185 \
    && git -C /opt/upstream/SeedVR checkout -q FETCH_HEAD
RUN --mount=type=cache,target=/root/.cache/uv --mount=type=secret,id=extra_ca,required=false \
    if [ -s /run/secrets/extra_ca ]; then export SSL_CERT_FILE=/run/secrets/extra_ca; fi; \
    uv pip install --extra-index-url https://download.pytorch.org/whl/cu121 -r /opt/upstream/SeedVR/requirements.txt
RUN git init -q /opt/upstream/apex && git -C /opt/upstream/apex remote add origin https://github.com/NVIDIA/apex \
    && git -C /opt/upstream/apex fetch -q --depth 1 origin 575968bc1f9127ccd61003a681472a83af4ff1a1 \
    && git -C /opt/upstream/apex checkout -q FETCH_HEAD
RUN --mount=type=cache,target=/root/.cache/uv --mount=type=secret,id=extra_ca,required=false \
    if [ -s /run/secrets/extra_ca ]; then export SSL_CERT_FILE=/run/secrets/extra_ca; fi; \
    uv pip install --no-build-isolation --config-settings "--build-option=--cpp_ext" --config-settings "--build-option=--cuda_ext" /opt/upstream/apex
RUN --mount=type=cache,target=/root/.cache/uv --mount=type=secret,id=extra_ca,required=false \
    if [ -s /run/secrets/extra_ca ]; then export SSL_CERT_FILE=/run/secrets/extra_ca; fi; \
    uv pip install --extra-index-url https://download.pytorch.org/whl/cu121 --no-build-isolation-package flash_attn flash_attn==2.5.9.post1
COPY packages/py/ce_contracts /src/packages/py/ce_contracts
COPY packages/py/ce_plugin_kit /src/packages/py/ce_plugin_kit
COPY packages/py/ce_worker /src/packages/py/ce_worker
COPY plugins/video/seedvr2 /src/plugins/video/seedvr2
RUN --mount=type=cache,target=/root/.cache/uv --mount=type=secret,id=extra_ca,required=false \
    if [ -s /run/secrets/extra_ca ]; then export SSL_CERT_FILE=/run/secrets/extra_ca; fi; \
    uv pip install /src/packages/py/ce_contracts /src/packages/py/ce_plugin_kit /src/packages/py/ce_worker /src/plugins/video/seedvr2
ENV WORKER_RUNTIME_FAMILY=post WORKER_ADAPTERS=seedvr2_3b APP_ENV=prod MODEL_CACHE_DIR=/models PYTHONPATH=/opt/upstream/SeedVR
WORKDIR /app
USER ce
CMD ["python", "-m", "ce_worker"]

# ---------------------------------------------------------------- rife
FROM nvidia/cuda:12.8.1-cudnn-runtime-ubuntu24.04@sha256:ac55d124da4882b497f732d8dfd9a702d5447a5f29d08d56da6f64f0a1eb34bc AS rife
ENV DEBIAN_FRONTEND=noninteractive PYTHONUNBUFFERED=1 UV_COMPILE_BYTECODE=1 UV_LINK_MODE=copy \
    UV_PYTHON_INSTALL_DIR=/opt/python VIRTUAL_ENV=/app/.venv PATH=/app/.venv/bin:$PATH
RUN apt-get update && apt-get install -y --no-install-recommends ca-certificates ffmpeg git curl \
    && rm -rf /var/lib/apt/lists/* && useradd --create-home --uid 10001 ce && mkdir -p /models /app \
    && chown ce:ce /models
COPY --from=uv /uv /usr/local/bin/uv
RUN --mount=type=secret,id=extra_ca,required=false \
    if [ -s /run/secrets/extra_ca ]; then export SSL_CERT_FILE=/run/secrets/extra_ca; fi; \
    uv python install 3.10 && uv venv /app/.venv --python 3.10
RUN --mount=type=cache,target=/root/.cache/uv --mount=type=secret,id=extra_ca,required=false \
    if [ -s /run/secrets/extra_ca ]; then export SSL_CERT_FILE=/run/secrets/extra_ca; fi; \
    uv pip install --index-url https://download.pytorch.org/whl/cu128 torch==2.8.0 torchvision==0.23.0 torchaudio==2.8.0
COPY packages/py/ce_contracts /src/packages/py/ce_contracts
COPY packages/py/ce_plugin_kit /src/packages/py/ce_plugin_kit
COPY packages/py/ce_worker /src/packages/py/ce_worker
COPY plugins/video/rife /src/plugins/video/rife
RUN --mount=type=cache,target=/root/.cache/uv --mount=type=secret,id=extra_ca,required=false \
    if [ -s /run/secrets/extra_ca ]; then export SSL_CERT_FILE=/run/secrets/extra_ca; fi; \
    uv pip install /src/packages/py/ce_contracts /src/packages/py/ce_plugin_kit /src/packages/py/ce_worker /src/plugins/video/rife
ENV WORKER_RUNTIME_FAMILY=post WORKER_ADAPTERS=rife_425 APP_ENV=prod MODEL_CACHE_DIR=/models
WORKDIR /app
USER ce
CMD ["python", "-m", "ce_worker"]
