# syntax=docker/dockerfile:1.7
# GENERATED by scripts/gen_worker_dockerfiles.py from infra/docker/families.yaml and the plugin manifests —
# do not edit by hand. The `audio` GPU runtime family (§36, ADR 0052): one build target per variant.
#   docker build -f infra/docker/worker-audio.Dockerfile --target <variant> -t creator-engine/worker-audio:<variant> .
# Variants: acestep (acestep_v15), moss_sfx (moss_sfx_v2).
# Status: lint-checked only; never built with its CUDA stack here (no GPU, rule 5). Weights come from the
# model cache at run time (MODEL_CACHE_DIR, a network volume or local disk), never from the image.

FROM ghcr.io/astral-sh/uv@sha256:df4cae8f3a96d175e2e5f992e597550000edbe78fdc2594d5cd8de1a217f504c AS uv

# ---------------------------------------------------------------- acestep
FROM nvidia/cuda:12.8.1-cudnn-runtime-ubuntu24.04@sha256:ac55d124da4882b497f732d8dfd9a702d5447a5f29d08d56da6f64f0a1eb34bc AS acestep
ENV DEBIAN_FRONTEND=noninteractive PYTHONUNBUFFERED=1 UV_COMPILE_BYTECODE=1 UV_LINK_MODE=copy \
    UV_PYTHON_INSTALL_DIR=/opt/python VIRTUAL_ENV=/app/.venv PATH=/app/.venv/bin:$PATH
RUN apt-get update && apt-get install -y --no-install-recommends ca-certificates ffmpeg git curl \
    && rm -rf /var/lib/apt/lists/* && useradd --create-home --uid 10001 ce && mkdir -p /models /app \
    && chown ce:ce /models
COPY --from=uv /uv /usr/local/bin/uv
RUN --mount=type=secret,id=extra_ca,required=false \
    if [ -s /run/secrets/extra_ca ]; then export SSL_CERT_FILE=/run/secrets/extra_ca; fi; \
    uv python install 3.11 && uv venv /app/.venv --python 3.11
RUN --mount=type=cache,target=/root/.cache/uv --mount=type=secret,id=extra_ca,required=false \
    if [ -s /run/secrets/extra_ca ]; then export SSL_CERT_FILE=/run/secrets/extra_ca; fi; \
    uv pip install --index-url https://download.pytorch.org/whl/cu128 torch==2.10.0 torchvision==0.25.0 torchaudio==2.10.0
RUN git init -q /opt/upstream/ACE-Step-1.5 && git -C /opt/upstream/ACE-Step-1.5 remote add origin https://github.com/ace-step/ACE-Step-1.5 \
    && git -C /opt/upstream/ACE-Step-1.5 fetch -q --depth 1 origin ca1e85fe9430179831e6bc6be790c332190a3866 \
    && git -C /opt/upstream/ACE-Step-1.5 checkout -q FETCH_HEAD
RUN --mount=type=cache,target=/root/.cache/uv --mount=type=secret,id=extra_ca,required=false \
    if [ -s /run/secrets/extra_ca ]; then export SSL_CERT_FILE=/run/secrets/extra_ca; fi; \
    uv pip install --extra-index-url https://download.pytorch.org/whl/cu128 /opt/upstream/ACE-Step-1.5
COPY packages/py/ce_contracts /src/packages/py/ce_contracts
COPY packages/py/ce_plugin_kit /src/packages/py/ce_plugin_kit
COPY packages/py/ce_worker /src/packages/py/ce_worker
COPY plugins/audio/acestep /src/plugins/audio/acestep
RUN --mount=type=cache,target=/root/.cache/uv --mount=type=secret,id=extra_ca,required=false \
    if [ -s /run/secrets/extra_ca ]; then export SSL_CERT_FILE=/run/secrets/extra_ca; fi; \
    uv pip install /src/packages/py/ce_contracts /src/packages/py/ce_plugin_kit /src/packages/py/ce_worker /src/plugins/audio/acestep
ENV WORKER_RUNTIME_FAMILY=audio WORKER_ADAPTERS=acestep_v15 APP_ENV=prod MODEL_CACHE_DIR=/models
WORKDIR /app
USER ce
CMD ["python", "-m", "ce_worker"]

# ---------------------------------------------------------------- moss_sfx
FROM nvidia/cuda:12.8.1-cudnn-runtime-ubuntu24.04@sha256:ac55d124da4882b497f732d8dfd9a702d5447a5f29d08d56da6f64f0a1eb34bc AS moss_sfx
ENV DEBIAN_FRONTEND=noninteractive PYTHONUNBUFFERED=1 UV_COMPILE_BYTECODE=1 UV_LINK_MODE=copy \
    UV_PYTHON_INSTALL_DIR=/opt/python VIRTUAL_ENV=/app/.venv PATH=/app/.venv/bin:$PATH
RUN apt-get update && apt-get install -y --no-install-recommends ca-certificates ffmpeg git curl \
    && rm -rf /var/lib/apt/lists/* && useradd --create-home --uid 10001 ce && mkdir -p /models /app \
    && chown ce:ce /models
COPY --from=uv /uv /usr/local/bin/uv
RUN --mount=type=secret,id=extra_ca,required=false \
    if [ -s /run/secrets/extra_ca ]; then export SSL_CERT_FILE=/run/secrets/extra_ca; fi; \
    uv python install 3.12 && uv venv /app/.venv --python 3.12
RUN --mount=type=cache,target=/root/.cache/uv --mount=type=secret,id=extra_ca,required=false \
    if [ -s /run/secrets/extra_ca ]; then export SSL_CERT_FILE=/run/secrets/extra_ca; fi; \
    uv pip install --index-url https://download.pytorch.org/whl/cu128 torch==2.9.1 torchaudio==2.9.1
RUN git init -q /opt/upstream/MOSS-TTS && git -C /opt/upstream/MOSS-TTS remote add origin https://github.com/OpenMOSS/MOSS-TTS \
    && git -C /opt/upstream/MOSS-TTS fetch -q --depth 1 origin 934d6826b084c46a0d033402174d5f8ac4ed2519 \
    && git -C /opt/upstream/MOSS-TTS checkout -q FETCH_HEAD
RUN --mount=type=cache,target=/root/.cache/uv --mount=type=secret,id=extra_ca,required=false \
    if [ -s /run/secrets/extra_ca ]; then export SSL_CERT_FILE=/run/secrets/extra_ca; fi; \
    uv pip install --extra-index-url https://download.pytorch.org/whl/cu128 /opt/upstream/MOSS-TTS
RUN --mount=type=cache,target=/root/.cache/uv --mount=type=secret,id=extra_ca,required=false \
    if [ -s /run/secrets/extra_ca ]; then export SSL_CERT_FILE=/run/secrets/extra_ca; fi; \
    uv pip install --extra-index-url https://download.pytorch.org/whl/cu128 torchcodec==0.8.1
COPY packages/py/ce_contracts /src/packages/py/ce_contracts
COPY packages/py/ce_plugin_kit /src/packages/py/ce_plugin_kit
COPY packages/py/ce_worker /src/packages/py/ce_worker
COPY plugins/audio/moss_sfx /src/plugins/audio/moss_sfx
RUN --mount=type=cache,target=/root/.cache/uv --mount=type=secret,id=extra_ca,required=false \
    if [ -s /run/secrets/extra_ca ]; then export SSL_CERT_FILE=/run/secrets/extra_ca; fi; \
    uv pip install /src/packages/py/ce_contracts /src/packages/py/ce_plugin_kit /src/packages/py/ce_worker /src/plugins/audio/moss_sfx
ENV WORKER_RUNTIME_FAMILY=audio WORKER_ADAPTERS=moss_sfx_v2 APP_ENV=prod MODEL_CACHE_DIR=/models
WORKDIR /app
USER ce
CMD ["python", "-m", "ce_worker"]
