// ESLint flat config for the JS/TS workspace, including the Next.js app (hooks rules for apps/web).
import js from "@eslint/js";
import reactHooks from "eslint-plugin-react-hooks";
import tseslint from "typescript-eslint";

export default tseslint.config(
  {
    ignores: [
      "**/node_modules/**",
      "**/.next/**",
      "**/dist/**",
      ".venv/**",
      "packages/py/**",
      "apps/api/**",
      "apps/orchestrator/**",
      "apps/scheduler/**",
      "apps/gpu-worker/**",
      "apps/render-worker/**",
      // generated by make gen-schema / make gen-client
      "packages/ts/api-client/src/models.ts",
      "packages/ts/api-client/src/api.ts",
    ],
  },
  js.configs.recommended,
  ...tseslint.configs.strict,
  {
    files: ["apps/web/**/*.{ts,tsx}"],
    plugins: { "react-hooks": reactHooks },
    rules: { "react-hooks/rules-of-hooks": "error", "react-hooks/exhaustive-deps": "error" },
  },
);
