"""Phase 8 tooling: license blocks (rule 15) and the generated GPU family Dockerfiles (§36) stay
consistent with the plugin manifests."""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[2]
FAMILIES = ("image", "wan", "tts", "asr", "audio", "vllm", "post", "lipsync", "vision")


def _run(*args: str) -> subprocess.CompletedProcess[str]:
    return subprocess.run([sys.executable, *args], cwd=ROOT, capture_output=True, text=True, check=False)


def test_every_license_block_is_complete_and_pinned() -> None:
    result = _run("scripts/verify_licenses.py")
    assert result.returncode == 0, result.stdout + result.stderr
    assert "\nerror" not in "\n" + result.stdout


def test_family_dockerfiles_are_fresh_and_cover_every_gpu_adapter() -> None:
    result = _run("scripts/gen_worker_dockerfiles.py", "--check")
    assert result.returncode == 0, result.stderr
    for family in FAMILIES:
        text = (ROOT / "infra" / "docker" / f"worker-{family}.Dockerfile").read_text(encoding="utf-8")
        assert "GENERATED by scripts/gen_worker_dockerfiles.py" in text
        assert 'CMD ["python", "-m", "ce_worker"]' in text and "USER ce" in text
        assert "@sha256:" in text  # bases pinned by digest


def test_family_generator_rejects_an_unassigned_adapter() -> None:
    sys.path.insert(0, str(ROOT / "scripts"))
    try:
        import gen_worker_dockerfiles as gen
    finally:
        sys.path.pop(0)
    config = yaml.safe_load((ROOT / "infra" / "docker" / "families.yaml").read_text(encoding="utf-8"))
    del config["variants"]["rife"]
    _, errors = gen.plan(config, gen.manifests())
    assert any("rife_425" in e and "no variant" in e for e in errors)


def test_models_doc_is_fresh() -> None:
    result = _run("scripts/gen_models_doc.py", "--check")
    assert result.returncode == 0, result.stderr
